Merge various cleanups from /changes/mtp/cleanups into /trunk:
 - svn merge https://google-secure-data-connector.googlecode.com/svn/trunk/data-connector-agent/ 
   https://google-secure-data-connector.googlecode.com/svn/changes/mtp/cleanups/data-connector-agent/
   .

- Added a variety of SVN metadata to files---svn:executable and svn:keywords $Id$.

- Updated the build and maintainer scripts so that the client can be installed
  in a way such that multiple versions can coexist on the same machine without
  having file namespace collisions.

- Refactored bits of the build infrastructure.

- Refactored bits of the maintainence scripts.

- Updated JAR third-party JAR references where applicable due to historical
  version divergences.

diff --git a/trunk/data-connector-agent/initscript-dist b/trunk/data-connector-agent/initscript-dist
--- a/trunk/data-connector-agent/initscript-dist
+++ b/trunk/data-connector-agent/initscript-dist
@@ -1,7 +1,5 @@
 #! /bin/bash
 #
-# $Id$
-#
 # Copyright 2008 Google Inc.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -16,6 +14,7 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 #
+# $Id$
 
 ### BEGIN INIT INFO
 # Provides:          dataconnector
@@ -34,65 +33,44 @@
 
 # Do NOT "set -e"
 
+FULLNAME=google-secure-data-connector-1.1
+INITSCRIPT=/etc/init.d/google-secure-data-connector-1.1
+BINDIR=/opt/google/secure-data-connector/1.1/bin
+LIBDIR=/opt/google/secure-data-connector/1.1/lib
+LOCALSTATEDIR=/var/opt/google/secure-data-connector/1.1/lib
+LOGDIR=/var/opt/google/secure-data-connector/1.1/log
+RUNDIR=/var/opt/google/secure-data-connector/1.1/run
+SYSCONFDIR=/etc/opt/google/secure-data-connector/1.1
+VERSION=1.1
+
+RULES_FILE="${LOCALSTATEDIR}/rules"
+LOGFILE="${LOGDIR}/dataconnector"
+PID_FILE="${RUNDIR}/${FULLNAME}"
+START_TIMEOUT=15
+
 # PATH should only include /usr/* if it runs after the mountnfs.sh script
 PATH=/usr/sbin:/usr/bin:/sbin:/bin
 DESC="Securelink client for Google Apps"
 NAME="dataconnector"
 
-JVM_ARGS="-Djava.net.preferIPv4Stack=true"
-CLIENT="com.google.dataconnector.client.Client"
-SECURELINK_HOME="/opt/dataconnector"
-CLASSPATH=\
-${SECURELINK_HOME}/third-party/jsocks/jsocks-server.jar:\
-${SECURELINK_HOME}/third-party//wpg-proxy/bin/wpgproxy.jar:\
-${SECURELINK_HOME}/third-party/jline/jline-0.9.91.jar:\
-${SECURELINK_HOME}/third-party/commons-io/commons-io-1.3.2.jar:\
-${SECURELINK_HOME}/third-party/jsch/jsch-20071024.jar:\
-${SECURELINK_HOME}/third-party/apache-log4j/log4j-1.2.15.jar:\
-${SECURELINK_HOME}/third-party/commons-logging/commons-logging-1.1.jar:\
-${SECURELINK_HOME}/third-party/commons-cli/commons-cli-1.1.jar:\
-${SECURELINK_HOME}/third-party/aopalliance/aopalliance.jar:\
-${SECURELINK_HOME}/third-party/guice-snapshot20081016/guice-assistedinject-snapshot20081016.jar:\
-${SECURELINK_HOME}/third-party/guice-snapshot20081016/guice-snapshot20081016.jar:\
-${SECURELINK_HOME}/third-party/json/json.jar:\
-${SECURELINK_HOME}/third-party/oauth/core.jar:\
-${SECURELINK_HOME}/third-party/oauth/commons-codec-1.3.jar:\
-${SECURELINK_HOME}/third-party/google-feedserver/commons-beanutils-1.8.0.jar:\
-${SECURELINK_HOME}/third-party/google-feedserver/commons-beanutils-core-1.8.0.jar:\
-${SECURELINK_HOME}/third-party/google-feedserver/gdata-client-1.0.jar:\
-${SECURELINK_HOME}/third-party/google-feedserver/gdata-core-1.0.jar:\
-${SECURELINK_HOME}/third-party/google-feedserver/google-feedserver-java-client-1.0.jar:\
-${SECURELINK_HOME}/third-party/google-feedserver/commons-lang-2.4.jar:\
-${SECURELINK_HOME}/classes/
+DAEMON=$(which java)
 
-CONFIG="/etc/opt/dataconnector/localConfig.xml"
-RULES="/etc/opt/dataconnector/resourceRules.xml"
-LOGGING="/etc/opt/dataconnector/logging.properties"
-KEY="/etc/opt/dataconnector/secureLinkClientTrustStore"
-KEY_PASS="woodstock"
-SERVER="apps-secure-data-connector.google.com"
-PORT="443"
-LOGFILE="/var/log/dataconnector/dataconnector"
-
-OPTIONS="-localConfigFile ${CONFIG} -rulesFile ${RULES}"
-
-DAEMON="/usr/bin/java"
-USER=dataconnector
-DAEMON_ARGS="${JVM_ARGS} -classpath ${CLASSPATH} ${CLIENT} ${OPTIONS}"
-PIDFILE=/var/run/${NAME}
-RULES_FILE=/var/opt/${NAME}/rules
-SCRIPTNAME=/etc/init.d/${NAME}
+[ -x "${DAEMON}" ] || { echo "No Java interpreter found!" >&2 ; exit 1 ; }
 
 START_MARKER="-- Starting dataconnector --"
 STOP_MARKER="-- Stopped dataconnector --"
 
-START_TIMEOUT=15
+create_directory_if_absent() {
+  directory="${!1}"
 
-# Exit if java is not installed
-[ -x /usr/bin/java ] || exit 0
+  if [ ! -d "${directory}" ]; then
+    mkdir -p "${directory}"
+  fi
+}
 
-# Read configuration variable file if it is present
-[ -r "/etc/default/${NAME}" ] && . "/etc/default/${NAME}"
+create_directory_if_absent LOGDIR
+create_directory_if_absent LOCALSTATEDIR
+create_directory_if_absent RUNDIR
 
 # Load the VERBOSE setting and other rcS variables
 [ -f /etc/default/rcS ] && . /etc/default/rcS
@@ -102,12 +80,23 @@ START_TIMEOUT=15
 . /lib/lsb/init-functions
 
 
+# Returns 0 if the agent is running.
+# Returns 1 if the agent is not running.
 is_running()
 {
-  # Returns 0 if the agent is running.
-  # Returns 1 if the agent is not running.
-  pgrep -f 'su securedataconnector' > /dev/null 2>&1
-  return $?
+  # There is a chance that multiple agents of different releases are running.
+
+  # If no PID file is present, do not consider it running.
+  [ -f "${PID_FILE}" ] || return 1
+
+  # Make sure that the provided PID looks to be the agent.
+  pid=$(< "${PID_FILE}")
+  if ps -p ${pid} -o comm,args | tail -1 | grep -q runclient.sh; then
+    return 0
+  else
+    echo "Google Secure Data Connector is not running according to ${PID_FILE}" >&2
+    return 1
+  fi
 }
 
 
@@ -197,7 +186,6 @@ check_startup()
 #
 do_start()
 {
-  start_cmd="nohup ${DAEMON} ${DAEMON_ARGS} >> \"${LOGFILE}\" 2>&1"
   # Return
   #   0 if daemon has been started
   #   1 if daemon was already running
@@ -209,8 +197,10 @@ do_start()
       ;;
     1)# Is not running. Start it.
       echo ${START_MARKER} >> "${LOGFILE}"
-      # Starts the dataconnector client backgrounded and returns its PID
-      sudo -u ${USER} /bin/bash -c "${start_cmd} & echo \$! "
+
+      # start.sh emits the PID of the runner agent script.
+      last_pid=$( "${BINDIR}"/start.sh )
+
       # Make sure the client started
       if [[ is_running ]]; then
         # Monitor the startup logs to confirm the agent connected OK.
@@ -239,18 +229,16 @@ do_stop()
   #   2 if daemon could not be stopped
   is_running
   case "$?" in
-    0) pid=$(pgrep -f "su securedataconnector")
-       kill ${pid}
-       case "$?" in
-         0) echo ${STOP_MARKER} >> "${LOGFILE}"
-            # Sterilise the rules file
-            echo '' > "${RULES_FILE}"
-            return 0
-            ;;
-         *) echo "Stopping ${pid} failed" >> "${LOGFILE}"
-            return 2
-            ;;
-       esac
+    0) "${BINDIR}/stop.sh"
+       if (( ${?} == 0 )); then
+         echo ${STOP_MARKER} >> "${LOGFILE}"
+         # Sterilise the rules file
+         echo '' > "${RULES_FILE}"
+         return 0
+       else
+         echo "Stopping runner failed." >> "${LOGFILE}"
+         return 2
+       fi
        ;;
     1) echo ${STOP_MARKER} >> "${LOGFILE}"
        return 1
@@ -260,7 +248,7 @@ do_stop()
 
 case "$1" in
   start)
-    [ "${VERBOSE}" != "no" ] && log_daemon_msg "Starting ${DESC}" "${NAME}"
+    [ "${VERBOSE}" != "no" ] && log_daemon_msg "Starting ${DESC}" "${NAME}" "${VERSION}"
     do_start
     case "$?" in
       0|1) [ "${VERBOSE}" != "no" ] && log_end_msg 0 ;;
@@ -308,7 +296,7 @@ case "$1" in
     get_rules
     ;;
   *)
-    echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload|get_rules}" >&2
+    echo "Usage: ${INITSCRIPT} {start|stop|status|restart|force-reload|get_rules}" >&2
     exit 3
     ;;
 esac
