Clean up the initscript and make it more robust: - Sanitize some of the script to use quoted variables and other safe tests. - Enable to the initscript to know whether the agent is running outside of the   PID file, due to cases where the agent may have been manually started.

diff --git a/data-connector-agent/distribute/debian/securedataconnector b/data-connector-agent/distribute/debian/securedataconnector
--- a/data-connector-agent/distribute/debian/securedataconnector
+++ b/data-connector-agent/distribute/debian/securedataconnector
@@ -1,5 +1,7 @@
 #! /bin/bash
 #
+# $Id$
+#
 # Copyright 2008 Google Inc.
 #
 # Licensed under the Apache License, Version 2.0 (the "License");
@@ -13,7 +15,7 @@
 # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 # See the License for the specific language governing permissions and
 # limitations under the License.
-#   
+#
 
 ### BEGIN INIT INFO
 # Provides:          dataconnector
@@ -41,27 +43,27 @@ JVM_ARGS="-Djava.net.preferIPv4Stack=true"
 CLIENT="com.google.dataconnector.client.Client"
 SECURELINK_HOME="/opt/dataconnector"
 CLASSPATH=\
-$SECURELINK_HOME/third-party/jsocks/jsocks-server.jar:\
-$SECURELINK_HOME/third-party//wpg-proxy/bin/wpgproxy.jar:\
-$SECURELINK_HOME/third-party/jline/jline-0.9.91.jar:\
-$SECURELINK_HOME/third-party/commons-io/commons-io-1.3.2.jar:\
-$SECURELINK_HOME/third-party/jsch/jsch-20071024.jar:\
-$SECURELINK_HOME/third-party/apache-log4j/log4j-1.2.15.jar:\
-$SECURELINK_HOME/third-party/commons-logging/commons-logging-1.1.jar:\
-$SECURELINK_HOME/third-party/commons-cli/commons-cli-1.1.jar:\
-$SECURELINK_HOME/third-party/aopalliance/aopalliance.jar:\
-$SECURELINK_HOME/third-party/guice-snapshot20081016/guice-assistedinject-snapshot20081016.jar:\
-$SECURELINK_HOME/third-party/guice-snapshot20081016/guice-snapshot20081016.jar:\
-$SECURELINK_HOME/third-party/json/json.jar:\
-$SECURELINK_HOME/third-party/oauth/core.jar:\
-$SECURELINK_HOME/third-party/oauth/commons-codec-1.3.jar:\
-$SECURELINK_HOME/third-party/google-feedserver/commons-beanutils-1.8.0.jar:\
-$SECURELINK_HOME/third-party/google-feedserver/commons-beanutils-core-1.8.0.jar:\
-$SECURELINK_HOME/third-party/google-feedserver/gdata-client-1.0.jar:\
-$SECURELINK_HOME/third-party/google-feedserver/gdata-core-1.0.jar:\
-$SECURELINK_HOME/third-party/google-feedserver/google-feedserver-java-client-1.0.jar:\
-$SECURELINK_HOME/third-party/google-feedserver/commons-lang-2.4.jar:\
-$SECURELINK_HOME/classes/
+${SECURELINK_HOME}/third-party/jsocks/jsocks-server.jar:\
+${SECURELINK_HOME}/third-party//wpg-proxy/bin/wpgproxy.jar:\
+${SECURELINK_HOME}/third-party/jline/jline-0.9.91.jar:\
+${SECURELINK_HOME}/third-party/commons-io/commons-io-1.3.2.jar:\
+${SECURELINK_HOME}/third-party/jsch/jsch-20071024.jar:\
+${SECURELINK_HOME}/third-party/apache-log4j/log4j-1.2.15.jar:\
+${SECURELINK_HOME}/third-party/commons-logging/commons-logging-1.1.jar:\
+${SECURELINK_HOME}/third-party/commons-cli/commons-cli-1.1.jar:\
+${SECURELINK_HOME}/third-party/aopalliance/aopalliance.jar:\
+${SECURELINK_HOME}/third-party/guice-snapshot20081016/guice-assistedinject-snapshot20081016.jar:\
+${SECURELINK_HOME}/third-party/guice-snapshot20081016/guice-snapshot20081016.jar:\
+${SECURELINK_HOME}/third-party/json/json.jar:\
+${SECURELINK_HOME}/third-party/oauth/core.jar:\
+${SECURELINK_HOME}/third-party/oauth/commons-codec-1.3.jar:\
+${SECURELINK_HOME}/third-party/google-feedserver/commons-beanutils-1.8.0.jar:\
+${SECURELINK_HOME}/third-party/google-feedserver/commons-beanutils-core-1.8.0.jar:\
+${SECURELINK_HOME}/third-party/google-feedserver/gdata-client-1.0.jar:\
+${SECURELINK_HOME}/third-party/google-feedserver/gdata-core-1.0.jar:\
+${SECURELINK_HOME}/third-party/google-feedserver/google-feedserver-java-client-1.0.jar:\
+${SECURELINK_HOME}/third-party/google-feedserver/commons-lang-2.4.jar:\
+${SECURELINK_HOME}/classes/
 
 CONFIG="/etc/opt/dataconnector/localConfig.xml"
 RULES="/etc/opt/dataconnector/resourceRules.xml"
@@ -72,14 +74,14 @@ SERVER="apps-secure-data-connector.google.com"
 PORT="443"
 LOGFILE="/var/log/dataconnector/dataconnector"
 
-OPTIONS="-localConfigFile $CONFIG -rulesFile $RULES"
+OPTIONS="-localConfigFile ${CONFIG} -rulesFile ${RULES}"
 
 DAEMON="/usr/bin/java"
 USER=dataconnector
-DAEMON_ARGS="$JVM_ARGS -classpath $CLASSPATH $CLIENT $OPTIONS"
-PIDFILE=/var/run/$NAME
-RULES_FILE=/var/opt/$NAME/rules
-SCRIPTNAME=/etc/init.d/$NAME
+DAEMON_ARGS="${JVM_ARGS} -classpath ${CLASSPATH} ${CLIENT} ${OPTIONS}"
+PIDFILE=/var/run/${NAME}
+RULES_FILE=/var/opt/${NAME}/rules
+SCRIPTNAME=/etc/init.d/${NAME}
 
 START_MARKER="-- Starting dataconnector --"
 STOP_MARKER="-- Stopped dataconnector --"
@@ -90,7 +92,7 @@ START_TIMEOUT=15
 [ -x /usr/bin/java ] || exit 0
 
 # Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
+[ -r "/etc/default/${NAME}" ] && . "/etc/default/${NAME}"
 
 # Load the VERBOSE setting and other rcS variables
 [ -f /etc/default/rcS ] && . /etc/default/rcS
@@ -102,18 +104,10 @@ START_TIMEOUT=15
 
 is_running()
 {
-  # Returns
-  # 0 if the service is running
-  # 1 if the service is not running
-  if [[ -e $PIDFILE ]]; then
-    read pid < $PIDFILE
-    # There should be a java process running with this PID
-    ps -o "args=" $pid | grep -q "java .* $CLIENT" && return 0
-    # Otherwise the service is dead. Remove the pidfile
-    rm $PIDFILE && return 1
-  else
-    return 1
-  fi
+  # Returns 0 if the agent is running.
+  # Returns 1 if the agent is not running.
+  pgrep -f 'su securedataconnector' > /dev/null 2>&1
+  return $?
 }
 
 
@@ -121,10 +115,10 @@ get_rules()
 {
   # Sweep back through the log to find the most recently registered rules.
   rule_match="ClientRegistrationUtil  - Registering rules: (.*)"
-  rules=$(tac "$LOGFILE" | while read line; do
-    [[ "$line" =~ $rule_match ]] && echo ${BASH_REMATCH[1]} && break
+  rules=$(tac "${LOGFILE}" | while read line; do
+    [[ "${line}" =~ "${rule_match}" ]] && echo ${BASH_REMATCH[1]} && break
     # Only process the log until we get to the previous session.
-    [[ "$line" =~ "$START_MARKER" || "$line" =~ "$STOP_MARKER" ]] && break
+    [[ "${line}" =~ "${START_MARKER}" || "${line}" =~ "${STOP_MARKER}" ]] && break
   done)
   echo $rules
 }
@@ -164,30 +158,30 @@ check_startup()
   # simply print it out as a bunch of numbers and capture it into a new
   # variable.
   declare -i timer=0
-  while [[ timer -lt $START_TIMEOUT ]] ; do
+  while (( ${timer} < ${START_TIMEOUT} )) ; do
     result=0
-    response=$(tac "$LOGFILE" | \
+    response=$(tac "${LOGFILE}" | \
       while read line; do
-        [[ "$line" =~ $match1 ]] && status[0]=0
-        [[ "$line" =~ $match2 ]] && status[1]=0
-        [[ "$line" =~ $match3 ]] && status[2]=0
-        [[ "$line" =~ $match4 ]] && status[3]=0
-        [[ "$line" =~ $match5 ]] && status[4]=0
-        [[ "$line" =~ $match6 ]] && status[5]=0
+        [[ "${line}" =~ "${match1}" ]] && status[0]=0
+        [[ "${line}" =~ "${match2}" ]] && status[1]=0
+        [[ "${line}" =~ "${match3}" ]] && status[2]=0
+        [[ "${line}" =~ "${match4}" ]] && status[3]=0
+        [[ "${line}" =~ "${match5}" ]] && status[4]=0
+        [[ "${line}" =~ "${match6}" ]] && status[5]=0
         # Only process the log until the start of this session
-        [[ "$line" =~ "$START_MARKER" ]] && echo ${status[@]} && break
+        [[ "${line}" =~ "${START_MARKER}" ]] && echo ${status[@]} && break
         # If we get here, the client failed to start normally.
-        [[ "$line" =~ "$STOP_MARKER" ]] && echo 128 && break
+        [[ "${line}" =~ "${STOP_MARKER}" ]] && echo 128 && break
       done)
-    for i in $response; do
+    for i in ${response}; do
       result+=${i}
     done
     # Results we should exit on:
     # - 0:  means all tests passed.
     # - 128: a processing error occurred.
-    if [[ $result -eq 0 ]]; then  # SUCCESS- all checks passed
+    if (( ${result} == 0 )); then  # SUCCESS- all checks passed
       return 0
-    elif [[ $result -eq 128 ]]; then  # HORROR- an error has caused ruin
+    elif (( ${result} == 128 )); then  # HORROR- an error has caused ruin
       return 1
     else  # PATIENCE- keep on truckin'
       timer+=1
@@ -203,7 +197,7 @@ check_startup()
 #
 do_start()
 {
-  start_cmd="nohup $DAEMON $DAEMON_ARGS >> $LOGFILE 2>&1"
+  start_cmd="nohup ${DAEMON} ${DAEMON_ARGS} >> \"${LOGFILE}\" 2>&1"
   # Return
   #   0 if daemon has been started
   #   1 if daemon was already running
@@ -214,17 +208,16 @@ do_start()
       return 1
       ;;
     1)# Is not running. Start it.
-      [[ -e $PIDFILE ]] && rm $PIDFILE
-      echo $START_MARKER >> $LOGFILE
+      echo ${START_MARKER} >> "${LOGFILE}"
       # Starts the dataconnector client backgrounded and returns its PID
-      sudo -u $USER /bin/bash -c "$start_cmd & echo \$! " > $PIDFILE
+      sudo -u ${USER} /bin/bash -c "${start_cmd} & echo \$! "
       # Make sure the client started
       if [[ is_running ]]; then
         # Monitor the startup logs to confirm the agent connected OK.
         check_startup
         started_ok=$?
-        if [[ $started_ok ]]; then
-          get_rules > $RULES_FILE
+        if [[ ${started_ok} ]]; then
+          get_rules > "${RULES_FILE}"
           return 0
         fi
       fi
@@ -246,24 +239,20 @@ do_stop()
   #   2 if daemon could not be stopped
   is_running
   case "$?" in
-    0) read pid < $PIDFILE
-       kill $pid
+    0) pid=$(pgrep -f "su securedataconnector")
+       kill ${pid}
        case "$?" in
-         0) [[ -e $PIDFILE ]] && rm $PIDFILE
-            echo $STOP_MARKER >> $LOGFILE
+         0) echo ${STOP_MARKER} >> "${LOGFILE}"
             # Sterilise the rules file
-            echo '' > $RULES_FILE
+            echo '' > "${RULES_FILE}"
             return 0
             ;;
-         *) echo "Stopping $pid failed" >> $LOGFILE
+         *) echo "Stopping ${pid} failed" >> "${LOGFILE}"
             return 2
             ;;
        esac
        ;;
-    1) echo $STOP_MARKER >> $LOGFILE
-       return 1
-       ;;
-    2) [[ -e $PIDFILE ]] && rm $PIDFILE
+    1) echo ${STOP_MARKER} >> "${LOGFILE}"
        return 1
        ;;
   esac
@@ -271,23 +260,23 @@ do_stop()
 
 case "$1" in
   start)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
+    [ "${VERBOSE}" != "no" ] && log_daemon_msg "Starting ${DESC}" "${NAME}"
     do_start
     case "$?" in
-      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+      0|1) [ "${VERBOSE}" != "no" ] && log_end_msg 0 ;;
+      2) [ "${VERBOSE}" != "no" ] && log_end_msg 1 ;;
     esac
     ;;
   stop)
-    [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
+    [ "${VERBOSE}" != "no" ] && log_daemon_msg "Stopping ${DESC}" "${NAME}"
     do_stop
     case "$?" in
-      0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
-      2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
+      0|1) [ "${VERBOSE}" != "no" ] && log_end_msg 0 ;;
+      2) [ "${VERBOSE}" != "no" ] && log_end_msg 1 ;;
     esac
     ;;
   restart|force-reload)
-    log_daemon_msg "Restarting $DESC" "$NAME"
+    log_daemon_msg "Restarting ${DESC}" "${NAME}"
     do_stop
     case "$?" in
       0|1)
@@ -306,7 +295,7 @@ case "$1" in
     esac
     ;;
   status)
-    log_daemon_msg "Checking $DESC" "$NAME"
+    log_daemon_msg "Checking ${DESC}" "${NAME}"
     is_running
     case "$?" in
       0) log_end_msg 0 ;;
