Remove Java as package install dependency and add script logic just to notify durning install.

diff --git a/data-connector-agent/third-party/pANTkage/spec_template b/data-connector-agent/third-party/pANTkage/spec_template
--- a/data-connector-agent/third-party/pANTkage/spec_template
+++ b/data-connector-agent/third-party/pANTkage/spec_template
@@ -152,6 +152,32 @@ dd if=/dev/urandom bs=1024 count=1 |passwd --stdin $CLIENT_USER
   chown -R $CLIENT_USER:$CLIENT_GROUP /etc/opt/%{name}/openssh/sshd_config
   chown -R $CLIENT_USER:$CLIENT_GROUP /etc/opt/%{name}/woodstock-user/.ssh/authorized_keys
 
+  # Check for java
+  echo "Checking for Java..."
+  if [ ${JAVA_HOME} ]; then
+    JAVABIN=${JAVA_HOME}/bin/java
+  elif [ ${JAVAHOME} ]; then
+    JAVABIN=${JAVAHOME}/bin/java
+  else # Try to figure it out.
+    JAVABIN=$(which java) >/dev/null 2>&1 || true
+  fi
+
+  if [ -x "${JAVABIN}" ]; then
+    ${JAVABIN} -version 2>&1 | grep 'version' |grep -q '1.6'
+    if [ $? != 0 ]; then
+      echo "Java found at ${JAVABIN} might not suitable."
+      echo "Secure Data Connector requires JRE 1.6 or higher"
+      exit 0
+    else
+      echo "Found java at ${JAVABIN}"
+    fi
+  else
+    echo "Java could not be found."
+    echo "Please install Java JRE 1.6 or higher before using the Secure Data Connector."
+    exit 0
+  fi
+
+
 
 %postun
 echo "Removing User Accounts.."
